Clientes y Churn

In [3]:
import pandas as pd
df_clientes = pd.read_csv('/Users/saraelbachouti/Desktop/UCV-Churn/data/raw/clientes.csv')
df_churn = pd.read_csv('data/raw/churn_target.csv')

In [14]:
df_clientes.info()
df_clientes.isnull().sum()
df_clientes.describe()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cliente_id        10000 non-null  str
 1   zona_id           10000 non-null  str
 2   region            10000 non-null  str
 3   tipo_zona         10000 non-null  str
 4   poblacion_zona    10000 non-null  int64
 5   edad              9700 non-null   float64
 6   sexo              9955 non-null   str
 7   estado_civil      9923 non-null   str
 8   num_lineas        10000 non-null  int64
 9   tipo_plan         10000 non-null  str
 10  tipo_dispositivo  10000 non-null  str
 11  ingreso_estimado  9700 non-null   float64
 12  antiguedad_meses  9700 non-null   float64
 13  descuento_activo  10000 non-null  int64
dtypes: float64(3), int64(3), str(8)
memory usage: 1.1 MB

,poblacion_zona,edad,num_lineas,ingreso_estimado,antiguedad_meses,descuento_activo
count,10000.000000,9700.000000,10000.000000,9700.000000,9700.000000,10000.000000
mean,60004.603000,39.341753,2.306600,3476.786701,32.551237,0.255000
std,28724.373885,11.973740,1.015726,1411.891561,22.525497,0.435883
min,11707.000000,18.000000,1.000000,900.000000,-110.000000,0.000000
25%,41163.000000,31.000000,2.000000,2466.000000,18.000000,0.000000
50%,56342.000000,39.000000,2.000000,3219.000000,29.000000,0.000000
75%,72683.000000,47.000000,3.000000,4194.250000,44.000000,1.000000
max,107159.000000,80.000000,5.000000,12000.000000,120.000000,1.000000

In [15]:
df_churn.info()
df_churn.isnull().sum()
df_churn.describe()

<class 'pandas.DataFrame'>
RangeIndex: 321987 entries, 0 to 321986
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   cliente_id  321987 non-null  str
 1   fecha       321987 non-null  str
 2   churn       321987 non-null  int64
dtypes: int64(1), str(2)
memory usage: 7.4 MB

               churn
count  321987.000000
mean        0.006211
std         0.078568
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000

In [16]:
df_churn.info()
df_churn["churn"].value_counts()

<class 'pandas.DataFrame'>
RangeIndex: 321987 entries, 0 to 321986
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   cliente_id  321987 non-null  str
 1   fecha       321987 non-null  str
 2   churn       321987 non-null  int64
dtypes: int64(1), str(2)
memory usage: 7.4 MB

churn
0    319987
1      2000
Name: count, dtype: int64

In [17]:
df_churn_final = df_churn.groupby("cliente_id")["churn"].max().reset_index()

In [18]:
df_clientes = df_clientes.drop_duplicates()

In [19]:
df_clientes.isnull().sum()

cliente_id            0
zona_id               0
region                0
tipo_zona             0
poblacion_zona        0
edad                300
sexo                 45
estado_civil         77
num_lineas            0
tipo_plan             0
tipo_dispositivo      0
ingreso_estimado    300
antiguedad_meses    300
descuento_activo      0
dtype: int64

In [20]:
df_clientes["edad"] = df_clientes["edad"].fillna(df_clientes["edad"].median())
df_clientes["ingreso_estimado"] = df_clientes["ingreso_estimado"].fillna(df_clientes["ingreso_estimado"].median())
df_clientes["antiguedad_meses"] = df_clientes["antiguedad_meses"].fillna(df_clientes["antiguedad_meses"].median())

df_clientes["sexo"] = df_clientes["sexo"].fillna("desconocido")
df_clientes["estado_civil"] = df_clientes["estado_civil"].fillna("desconocido")

In [21]:
df_clientes["tipo_plan"] = df_clientes["tipo_plan"].str.lower().str.strip()
df_clientes["region"] = df_clientes["region"].str.lower().str.strip()
df_clientes["tipo_zona"] = df_clientes["tipo_zona"].str.lower().str.strip()

In [22]:
df_clientes["edad"].describe()

count    10000.000000
mean        39.331500
std         11.792893
min         18.000000
25%         31.000000
50%         39.000000
75%         47.000000
max         80.000000
Name: edad, dtype: float64

In [25]:
df_clientes.to_csv('data/processed/clientes_cleaned.csv', index=False)

In [26]:
df_churn_final.to_csv('data/processed/churn_final_cleaned.csv', index=False)